[package]
name = "deno-scripting"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_core = "0.238.0"
paho-mqtt = "0.12.3"
log = "0.4.20"
rand = "0.8.5"
leaky-bucket = "1.0.1"
serde_json = "1.0.108"
tokio = { version = "1.35.0", features = ["full"] }
deno_net = "0.120.0"
